"""Monitoring setup and healthcheck alert commands."""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

from core.docker import run
from core.paths import resolve_root_dir
from core.ui import log_info, log_ok, log_warn
from core.validators import CommandError, fail, resolve_prompted_environment

from ._docker import DEFAULT_ROOT


def _uptimerobot_post(api_key: str, endpoint: str, **params) -> dict:
    import urllib.parse
    import urllib.request
    data = urllib.parse.urlencode({"api_key": api_key, "format": "json", **params}).encode()
    req = urllib.request.Request(
        f"https://api.uptimerobot.com/v2/{endpoint}",
        data=data,
        headers={"Content-Type": "application/x-www-form-urlencoded"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=15) as resp:
        return json.loads(resp.read())


_SKIP_MONITORING_ROUTES = frozenset({
    "seq", "aspire", "prometheus", "grafana", "alertmanager",
    "adminer", "phpmyadmin", "rabbitmq", "cadvisor", "i",
})

_HEALTH_PATHS: dict[str, str] = {
    "api": "/health/ready",
}


def _monitor_url(route_name: str, host: str, https_port: str) -> str:
    port_suffix = f":{https_port}" if https_port not in ("443", "") else ""
    path = _HEALTH_PATHS.get(route_name, "/")
    return f"https://{host}{port_suffix}{path}"


_CRON_WRAPPER_NAME = "healthcheck-alert-cron.sh"


def _write_healthcheck_alert_wrapper(root_dir: Path, environment: str) -> Path:
    """Write a wrapper shell script that cron will call directly.

    Values like ALERTS_EMAIL and SMTP_PASSWORD are read from the env file at
    runtime (not baked into the cron line), so the wrapper is immune to
    single-quote injection and stays correct after env file updates.
    """
    script = root_dir / "scripts" / "tools" / "monitoring" / "healthcheck_alert.py"
    env_file = root_dir / "generated" / environment / "deploy.env"
    log_dir = root_dir / "logs" / environment / "monitoring"
    log_file = log_dir / "healthcheck-alert.log"

    wrapper_path = root_dir / "generated" / environment / _CRON_WRAPPER_NAME
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by: scripts/cli.py tools setup-healthcheck-cron",
        "# Re-run the command to regenerate after env changes.",
        "set -a",
        f'source "{env_file}"',
        "set +a",
        f'exec "{sys.executable}" "{script}" \\',
        f'  --env {environment} \\',
        f'  --root "{root_dir}" \\',
        '  --alerts-email "${ALERTS_EMAIL:-}" \\',
        '  --smtp-host "${SMTP_HOST:-}" \\',
        '  --smtp-port "${SMTP_PORT:-587}" \\',
        '  --smtp-user "${SMTP_USER:-}" \\',
        f'  >> "{log_file}" 2>&1',
    ]
    wrapper_path.parent.mkdir(parents=True, exist_ok=True)
    wrapper_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    wrapper_path.chmod(0o700)
    return wrapper_path


def _healthcheck_alert_cron_line(root_dir: Path, environment: str) -> str:
    wrapper = root_dir / "generated" / environment / _CRON_WRAPPER_NAME
    return f"*/5 * * * * {wrapper}"


def _healthcheck_alert_cron_marker(environment: str) -> str:
    return f"tools/monitoring/healthcheck_alert.py --env {environment}"


def cmd_setup_monitoring(args: argparse.Namespace) -> int:
    from core.env import parse_env_file, parse_routes_file, resolve_runtime_env

    root_dir = resolve_root_dir(DEFAULT_ROOT, args.project_root)
    environment = resolve_prompted_environment(getattr(args, "environment", None))

    runtime_tmp_dir = root_dir / ".tmp" / "runtime"
    runtime_tmp_dir.mkdir(parents=True, exist_ok=True)
    runtime_env = resolve_runtime_env(root_dir, environment, runtime_tmp_dir)
    runtime_values = parse_env_file(runtime_env)

    api_key = args.api_key or runtime_values.get("UPTIMEROBOT_API_KEY", "")
    if not api_key:
        fail("UptimeRobot API key is required. Set UPTIMEROBOT_API_KEY in env or pass --api-key.")

    https_port = runtime_values.get("HTTPS_PORT", "443")

    routes_file = root_dir / "generated" / environment / "routes.env"
    if not routes_file.is_file():
        fail(f"routes.env not found: {routes_file}. Run generate-config first.")

    routes = parse_routes_file(routes_file)
    public_routes = [(name, host, target) for name, host, target in routes
                     if name not in _SKIP_MONITORING_ROUTES]

    if not public_routes:
        fail("No public routes found to monitor.")

    log_info(f"Routes to monitor ({environment}):")
    for name, host, _ in public_routes:
        url = _monitor_url(name, host, https_port)
        log_info(f"  {name:<16} {url}")

    if args.dry_run:
        log_ok("Dry run — no monitors created.")
        return 0

    existing = _uptimerobot_post(api_key, "getMonitors").get("monitors", [])
    existing_urls = {m["url"] for m in existing}

    contacts = _uptimerobot_post(api_key, "getAlertContacts").get("alert_contacts", [])
    if not contacts:
        fail("No alert contacts found in UptimeRobot account. Add one in the UptimeRobot dashboard.")
    alert_contact_str = f"{contacts[0]['id']}_0_0"

    created = 0
    skipped = 0
    for name, host, _ in public_routes:
        url = _monitor_url(name, host, https_port)
        if url in existing_urls:
            log_warn(f"  {name}: monitor already exists — skipped")
            skipped += 1
            continue

        friendly_name = f"{environment}-{name}"
        result = _uptimerobot_post(
            api_key, "newMonitor",
            friendly_name=friendly_name,
            url=url,
            type=1,
            interval=300,
            alert_contacts=alert_contact_str,
        )
        if result.get("stat") == "ok":
            log_ok(f"  {name}: monitor created ({url})")
            created += 1
        else:
            log_warn(f"  {name}: failed — {result.get('error', result)}")

    log_ok(f"Done: {created} created, {skipped} skipped.")
    return 0


def cmd_healthcheck_alert(args: argparse.Namespace) -> int:
    from core.env import parse_env_file, resolve_runtime_env

    root_dir = resolve_root_dir(DEFAULT_ROOT, args.project_root)
    environment = resolve_prompted_environment(getattr(args, "environment", None))

    runtime_tmp_dir = root_dir / ".tmp" / "runtime"
    runtime_tmp_dir.mkdir(parents=True, exist_ok=True)
    runtime_env = resolve_runtime_env(root_dir, environment, runtime_tmp_dir)
    runtime_values = parse_env_file(runtime_env)

    script = root_dir / "scripts" / "tools" / "monitoring" / "healthcheck_alert.py"
    if not script.is_file():
        fail(f"Script not found: {script}")

    alerts_email = runtime_values.get("ALERTS_EMAIL", "")
    if not alerts_email:
        fail("ALERTS_EMAIL is not set in the environment file.")

    cmd = [
        sys.executable, str(script),
        "--env", environment,
        "--root", str(root_dir),
        "--alerts-email", alerts_email,
        "--smtp-host", runtime_values.get("SMTP_HOST", ""),
        "--smtp-port", runtime_values.get("SMTP_PORT", "587"),
        "--smtp-user", runtime_values.get("SMTP_USER", ""),
    ]
    env = {**os.environ, "SMTP_PASSWORD": runtime_values.get("SMTP_PASSWORD", "")}
    result = run(cmd, cwd=root_dir, check=False, env=env)
    return result.returncode


def cmd_setup_healthcheck_cron(args: argparse.Namespace) -> int:
    from core.env import parse_env_file, resolve_runtime_env

    root_dir = resolve_root_dir(DEFAULT_ROOT, args.project_root)
    environment = resolve_prompted_environment(getattr(args, "environment", None))

    runtime_tmp_dir = root_dir / ".tmp" / "runtime"
    runtime_tmp_dir.mkdir(parents=True, exist_ok=True)
    runtime_env = resolve_runtime_env(root_dir, environment, runtime_tmp_dir)
    runtime_values = parse_env_file(runtime_env)

    alerts_email = runtime_values.get("ALERTS_EMAIL", "")
    if not alerts_email:
        fail("ALERTS_EMAIL is not set. Add it to env files and regenerate config first.")

    log_dir = root_dir / "logs" / environment / "monitoring"
    log_dir.mkdir(parents=True, exist_ok=True)

    wrapper = _write_healthcheck_alert_wrapper(root_dir, environment)
    cron_line = _healthcheck_alert_cron_line(root_dir, environment)
    marker = _healthcheck_alert_cron_marker(environment)
    log_info(f"Wrapper script: {wrapper}")

    print()
    log_info("Generated cron job:")
    print(f"  {cron_line}")
    print()

    if not runtime_values.get("SMTP_HOST"):
        log_warn("SMTP_HOST is not set — emails will be logged but not sent.")
    print()

    try:
        confirm_str = input("Apply? (y/n): ").strip().lower()
    except (EOFError, KeyboardInterrupt):
        print()
        raise CommandError("Aborted.")

    if confirm_str != "y":
        raise CommandError("Aborted.")

    existing_result = subprocess.run(["crontab", "-l"], capture_output=True, text=True)
    existing = existing_result.stdout if existing_result.returncode == 0 else ""
    lines = [line for line in existing.splitlines() if marker not in line]
    lines.append(cron_line)
    new_crontab = "\n".join(lines) + "\n"

    subprocess.run(["crontab", "-"], input=new_crontab, text=True, check=True)

    log_ok("Cron updated successfully")
    log_info(f"Alert logs: {log_dir}/healthcheck-alert.log")
    print()
    subprocess.run(["crontab", "-l"])
    return 0


def cmd_send_test_alert(args: argparse.Namespace) -> int:
    from core.env import parse_env_file, resolve_runtime_env

    root_dir = resolve_root_dir(DEFAULT_ROOT, args.project_root)
    environment = resolve_prompted_environment(getattr(args, "environment", None))

    runtime_tmp_dir = root_dir / ".tmp" / "runtime"
    runtime_tmp_dir.mkdir(parents=True, exist_ok=True)
    runtime_env = resolve_runtime_env(root_dir, environment, runtime_tmp_dir)
    runtime_values = parse_env_file(runtime_env)

    alerts_email = runtime_values.get("ALERTS_EMAIL", "")
    if not alerts_email:
        fail("ALERTS_EMAIL is not set in the environment file.")

    script = root_dir / "scripts" / "tools" / "monitoring" / "healthcheck_alert.py"
    if not script.is_file():
        fail(f"Script not found: {script}")

    env = {**os.environ, "SMTP_PASSWORD": runtime_values.get("SMTP_PASSWORD", "")}
    result = run(
        [
            sys.executable, str(script),
            "--env", environment,
            "--root", str(root_dir),
            "--alerts-email", alerts_email,
            "--smtp-host", runtime_values.get("SMTP_HOST", ""),
            "--smtp-port", runtime_values.get("SMTP_PORT", "587"),
            "--smtp-user", runtime_values.get("SMTP_USER", ""),
            "--test",
        ],
        cwd=root_dir,
        check=False,
        env=env,
    )
    return result.returncode
