#!/usr/bin/env python3
"""Stack command package.

Submodules:
  _common   — shared constants and utility helpers
  _health   — service health / readiness checks
  _rollback — image snapshot and rollback helpers
  _migrate  — EF Core migration helpers + cmd_migrate
  _swagger  — Swagger doc generation + cmd_swagger_gen
  _preflight — PreflightContext + cmd_preflight
  _smoke    — smoke test helpers + cmd_smoke
  _up       — cmd_up + cmd_down
  _cache    — cmd_cache_purge
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

if __package__ in {None, ""}:
    scripts_dir = Path(__file__).resolve().parents[2]
    cli_path = scripts_dir / "cli.py"
    raise SystemExit(subprocess.call([str(cli_path), "stack", *sys.argv[1:]]))

# ── Re-exports so tests using `from commands import stack; stack.<name>` keep working ──

from ._cache import cmd_cache_purge
from ._common import (
    BACKEND_SERVICE,
    DEFAULT_ROOT,
    FRONTEND_SWAGGER_DIR,
    MIGRATOR_PROFILE,
    MIGRATOR_SERVICE,
    NGINX_MEDIA_CACHE_DIR,
    NGINX_MEDIA_ROUTE_NAME,
    PREFLIGHT_CLEANUP_MOUNT,
    REQUIRED_STACK_SERVICES,
    SWAGGER_BACKEND_BASE_URL,
    SWAGGER_BACKEND_HEALTH_TIMEOUT,
    SWAGGER_DOCUMENTS,
    SWAGGER_PREBUILD_SERVICES,
    _built_service_image_name,
    _check_stack_running,
    _https_route_url,
    _load_compose_services,
    _media_route_host,
    _service_container_id,
    _show_compose_ps,
    _warn_nonstandard_public_ports,
)
from ._health import (
    _check_backend_readiness,
    _check_service_healths,
    _wait_for_service_health,
)
from ._migrate import _confirm_production_migrate, _run_migrator, cmd_migrate
from ._preflight import PreflightContext, cmd_preflight
from ._rollback import _restore_rollback_images, _snapshot_rollback_images
from ._smoke import _check_nginx_https, _check_nginx_route_health, cmd_smoke
from ._swagger import (
    _ensure_swagger_backend_image,
    _prepare_frontend_swagger,
    _restart_if_unhealthy,
    _swagger_prebuild_context,
    _write_swagger_document,
    cmd_swagger_gen,
)
from ._up import cmd_down, cmd_restart, cmd_up

# Third-party symbols that tests patch directly on the `stack` module object
from checks import preflight_checks  # noqa: F401
from core.compose_runner import create_compose_context  # noqa: F401
from core.docker import ComposeContext, run, run_compose  # noqa: F401
from core.ui import log_info, log_ok, log_warn  # noqa: F401
from core.validators import CommandError, ensure_command, fail, resolve_prompted_environment  # noqa: F401


def register(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    stack_parser = subparsers.add_parser("stack", help="Stack operations")
    stack_sub = stack_parser.add_subparsers(dest="stack_action", required=True)

    up_parser = stack_sub.add_parser("up", help="Start stack")
    up_parser.add_argument("environment", nargs="?")
    up_parser.add_argument("project_root", nargs="?")
    up_parser.add_argument("--dry-run", action="store_true", help="Validate compose up plan without starting containers")
    up_parser.add_argument("--skip-migrate", action="store_true", help="Skip the EF Core migrator before starting services")
    up_parser.add_argument("--observability", action="store_true", help="Also start observability services (Seq, Aspire Dashboard)")
    up_parser.add_argument("--no-rollback", action="store_true", dest="no_rollback", help="Skip automatic rollback on build/start failure")
    up_parser.add_argument("--no-build", action="store_true", dest="no_build", help="Start containers without rebuilding images; skips Swagger regeneration")
    up_parser.add_argument("--skip-swagger", action="store_true", dest="skip_swagger", help="Skip Swagger doc generation (use when already generated by a separate swagger-gen step)")
    up_parser.add_argument("--build-services", nargs="*", dest="build_services", metavar="SERVICE", default=None, help="Build only these specific services instead of all buildable services (e.g. --build-services backend media-worker nginx)")
    up_parser.set_defaults(handler=cmd_up)

    migrate_parser = stack_sub.add_parser("migrate", help="Run EF Core database migrations")
    migrate_parser.add_argument("environment", nargs="?")
    migrate_parser.add_argument("project_root", nargs="?")
    migrate_parser.add_argument("--dry-run", action="store_true", help="Validate migrator compose plan without starting containers")
    migrate_parser.set_defaults(handler=cmd_migrate)

    down_parser = stack_sub.add_parser("down", help="Stop stack")
    down_parser.add_argument("environment", nargs="?")
    down_parser.add_argument("project_root", nargs="?")
    down_parser.set_defaults(handler=cmd_down)

    preflight_parser = stack_sub.add_parser("preflight", help="Run preflight checks")
    preflight_parser.add_argument("environment", nargs="?")
    preflight_parser.add_argument("project_root", nargs="?")
    preflight_parser.add_argument("--isolated", action="store_true", help="Run preflight in a temporary isolated compose project")
    preflight_parser.add_argument("--dry-run", action="store_true", help="Use docker compose dry-run for container-start checks")
    preflight_parser.add_argument("--strict", action="store_true", help="Treat env warnings as failures and enable strict secret checks")
    preflight_parser.add_argument("--skip-connectivity-check", action="store_true", dest="skip_connectivity_check", help="Skip host internet connectivity and DNS resolution check")
    preflight_parser.add_argument("--no-header", action="store_true", help=argparse.SUPPRESS)

    strict_group = preflight_parser.add_mutually_exclusive_group()
    strict_group.add_argument("--strict-generated", dest="strict_generated", action="store_true")
    strict_group.add_argument("--no-strict-generated", dest="strict_generated", action="store_false")
    preflight_parser.set_defaults(strict_generated=None)

    regen_group = preflight_parser.add_mutually_exclusive_group()
    regen_group.add_argument("--allow-regenerate", dest="allow_regenerate", action="store_true")
    regen_group.add_argument("--no-allow-regenerate", dest="allow_regenerate", action="store_false")
    preflight_parser.set_defaults(allow_regenerate=None)
    preflight_parser.add_argument("--skip-swagger", action="store_true", dest="skip_swagger", help="Skip Swagger doc generation (use when already generated by a separate swagger-gen step)")
    preflight_parser.set_defaults(handler=cmd_preflight)

    swagger_gen_parser = stack_sub.add_parser("swagger-gen", help="Generate Swagger docs for the frontend API client")
    swagger_gen_parser.add_argument("environment", nargs="?")
    swagger_gen_parser.add_argument("project_root", nargs="?")
    swagger_gen_parser.add_argument("--dry-run", action="store_true", help="Validate compose plan without starting containers")
    swagger_gen_parser.set_defaults(handler=cmd_swagger_gen)

    smoke_parser = stack_sub.add_parser("smoke", help="Run smoke checks")
    smoke_parser.add_argument("environment", nargs="?")
    smoke_parser.add_argument("project_root", nargs="?")
    smoke_parser.add_argument("--no-header", action="store_true", help=argparse.SUPPRESS)
    smoke_parser.set_defaults(handler=cmd_smoke)

    restart_parser = stack_sub.add_parser(
        "restart",
        help="Restart one or more services without touching the rest of the stack",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Примеры:\n"
            "  ./scripts/cli.py stack restart nginx\n"
            "  ./scripts/cli.py stack restart nginx --env dev\n"
            "  ./scripts/cli.py stack restart backend --rebuild\n"
            "  ./scripts/cli.py stack restart backend media-worker\n"
            "  ./scripts/cli.py stack restart nginx --rebuild --env dev"
        ),
    )
    restart_parser.add_argument(
        "services",
        nargs="+",
        metavar="SERVICE",
        help="Имена сервисов для перезапуска (один или несколько)",
    )
    restart_parser.add_argument(
        "--rebuild",
        action="store_true",
        help="Пересобрать образ(ы) перед перезапуском (docker compose build)",
    )
    restart_parser.add_argument("--env", dest="environment", help="Окружение: dev|prod")
    restart_parser.add_argument("--project-root", dest="project_root")
    restart_parser.set_defaults(handler=cmd_restart)

    cache_purge_parser = stack_sub.add_parser("cache-purge", help="Purge nginx media CDN cache entries")
    cache_purge_parser.add_argument("environment", nargs="?")
    cache_purge_parser.add_argument("project_root", nargs="?")
    cache_purge_parser.add_argument(
        "--path",
        default="",
        metavar="PATH",
        help="Path of a specific media file to purge (e.g. /abc123def456). Omit to purge entire cache.",
    )
    cache_purge_parser.add_argument("-y", "--yes", action="store_true", help="Skip confirmation when purging all")
    cache_purge_parser.set_defaults(handler=cmd_cache_purge)
