#!/usr/bin/env bash
# =============================================================================
# scripts/tools/setup-events-watcher.sh — Установка systemd-сервиса для
# real-time мониторинга Docker-контейнеров.
#
# Что делает:
#   1. Генерирует wrapper-скрипт generated/<env>/events-watcher.sh
#      (sources deploy.env и запускает docker_events_watcher.py)
#   2. Устанавливает systemd unit yuviron-events-watcher@<env>.service
#      через sudo (требует пароль один раз)
#   3. Включает и запускает сервис
#
# Сервис перезапускается автоматически при сбое (Restart=always).
# Логи: logs/<env>/monitoring/events-watcher.log
#
# Запуск: ./scripts/tools/setup-events-watcher.sh [dev|prod]
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
PYTHON="$ROOT_DIR/.venv/bin/python"
WATCHER="$ROOT_DIR/scripts/tools/monitoring/docker_events_watcher.py"

ENVIRONMENT="${1:-}"
if [[ -z "$ENVIRONMENT" ]]; then
    read -rp "Environment (dev/prod): " ENVIRONMENT
fi

case "$ENVIRONMENT" in
    dev|prod) ;;
    *) echo "Error: unknown environment '$ENVIRONMENT'" >&2; exit 1 ;;
esac

DEPLOY_ENV="$ROOT_DIR/generated/$ENVIRONMENT/deploy.env"
if [[ ! -f "$DEPLOY_ENV" ]]; then
    echo "Error: $DEPLOY_ENV not found." >&2
    echo "Run: ./scripts/cli.py generate-config --env $ENVIRONMENT" >&2
    exit 1
fi

if [[ ! -f "$PYTHON" ]]; then
    echo "Error: virtualenv not found at $PYTHON" >&2
    echo "Run: python3 -m venv .venv && .venv/bin/pip install -r requirements.lock" >&2
    exit 1
fi

# ── Generate bash wrapper ─────────────────────────────────────────────────────

LOG_DIR="$ROOT_DIR/logs/$ENVIRONMENT/monitoring"
LOG_FILE="$LOG_DIR/events-watcher.log"
mkdir -p "$LOG_DIR"

WRAPPER="$ROOT_DIR/generated/$ENVIRONMENT/events-watcher.sh"
cat > "$WRAPPER" <<WRAPPER_EOF
#!/usr/bin/env bash
# Generated by: scripts/tools/setup-events-watcher.sh
# Re-run the command to regenerate after env changes.
set -a
source "$DEPLOY_ENV"
set +a
exec "$PYTHON" "$WATCHER" \\
  --env $ENVIRONMENT \\
  --root "$ROOT_DIR"
WRAPPER_EOF
chmod 700 "$WRAPPER"

# ── Systemd unit ──────────────────────────────────────────────────────────────

INSTANCE="yuviron-events-watcher@${ENVIRONMENT}"
UNIT_FILE="/etc/systemd/system/yuviron-events-watcher@.service"

UNIT_CONTENT="[Unit]
Description=Yuviron Docker events watcher (%i)
Documentation=https://github.com/Filippov-Nikolay/yuviron-server
After=docker.service
Wants=docker.service
StartLimitIntervalSec=0

[Service]
Type=simple
ExecStart=$ROOT_DIR/generated/%i/events-watcher.sh
Restart=always
RestartSec=15
StandardOutput=append:$ROOT_DIR/logs/%i/monitoring/events-watcher.log
StandardError=append:$ROOT_DIR/logs/%i/monitoring/events-watcher.log

[Install]
WantedBy=multi-user.target"

echo
echo "=== Systemd unit to install: $UNIT_FILE ==="
echo "$UNIT_CONTENT"
echo
echo "=== Wrapper: $WRAPPER ==="
cat "$WRAPPER"
echo
read -rp "Install and start $INSTANCE? (y/n): " CONFIRM

if [[ "$CONFIRM" != "y" ]]; then
    echo "Aborted."
    exit 0
fi

echo "$UNIT_CONTENT" | sudo tee "$UNIT_FILE" > /dev/null
sudo systemctl daemon-reload
sudo systemctl enable "$INSTANCE"
sudo systemctl restart "$INSTANCE"

echo
echo "✅ $INSTANCE started"
echo "   Logs:   $LOG_FILE"
echo "   Status: sudo systemctl status $INSTANCE"
echo "   Stop:   sudo systemctl stop $INSTANCE"
