routes:
  api:
    target: backend:5073
    client_max_body_size: 50m
    has_auth_endpoints: true
    environments: [dev, prod]

  client:
    app: client
    client_max_body_size: 5m
    environments: [dev, prod]

  admin:
    app: admin
    environments: [dev, prod]

  backoffice:
    app: backoffice
    environments: [dev, prod]

  seq:
    target: seq:80
    host_strategy: subdomain
    environments: [dev]

  aspire:
    target: aspire-dashboard:18888
    host_strategy: subdomain
    environments: [dev]
