routes:
  api:
    target: backend:5073
    client_max_body_size: 50m
    has_auth_endpoints: true
    rate_limit_zone: api_general
    upload_locations: [media, upload, uploads, files, file]
    upload_client_max_body_size: 50m
    upload_rate_limit_zone: api_upload
    upload_rate_limit_burst: 2
    environments: [dev, prod]

  client:
    app: client
    client_max_body_size: 5m
    environments: [dev, prod]

  admin:
    app: admin
    environments: [dev, prod]

  backoffice:
    app: backoffice
    environments: [dev, prod]

  seq:
    target: seq:80
    host_strategy: subdomain
    environments: [dev]

  aspire:
    target: aspire-dashboard:18888
    host_strategy: subdomain
    environments: [dev]

  i:
      target: backend:5073
      host_strategy: subdomain
      environments: [dev, prod]
      media_proxy: true
    