#!/usr/bin/env python3
from __future__ import annotations

import argparse
import ipaddress
import subprocess
import sys
from pathlib import Path

if __package__ in {None, ""}:
    scripts_dir = Path(__file__).resolve().parents[1]
    cli_path = scripts_dir / "cli.py"
    raise SystemExit(subprocess.call([str(cli_path), "dns", *sys.argv[1:]]))

from core.env import parse_routes_file
from core.paths import resolve_root_dir
from core.ui import log_info, log_ok
from core.validators import fail, resolve_prompted_environment, resolve_prompted_required, validate_domain


DEFAULT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_FORWARDERS = ("8.8.8.8", "1.1.1.1")


def _validate_ip(raw_ip: str) -> str:
    value = raw_ip.strip()
    if not value:
        fail("IP address must not be empty")

    try:
        return str(ipaddress.ip_address(value))
    except ValueError:
        fail(f"Invalid IP address: {value}")
        raise AssertionError("unreachable")


def _route_hosts(routes_file: Path, domain: str) -> list[str]:
    if not routes_file.is_file():
        fail(f"Routes file not found: {routes_file}. Run ./scripts/init.py --env <env> --domain {domain} --no-up first.")

    hosts: list[str] = []
    seen: set[str] = set()
    invalid_hosts: list[str] = []

    for _route_name, host, _upstream in parse_routes_file(routes_file):
        normalized = host.strip().rstrip(".").lower()
        if not normalized:
            continue
        if normalized != domain and not normalized.endswith(f".{domain}"):
            invalid_hosts.append(normalized)
            continue
        if normalized in seen:
            continue
        seen.add(normalized)
        hosts.append(normalized)

    if invalid_hosts:
        fail(f"Route hosts outside domain '{domain}': {', '.join(invalid_hosts)}")
    if not hosts:
        fail(f"No route hosts found in {routes_file}")

    return hosts


def render_corefile(
    *,
    environment: str,
    domain: str,
    ip_address: str,
    hosts: list[str],
    forwarders: tuple[str, ...] = DEFAULT_FORWARDERS,
) -> str:
    forwarder_list = " ".join(forwarders)
    host_lines = "\n".join(f"        {ip_address} {host}" for host in hosts)

    return (
        "# Generated by Yuviron CLI. Do not edit by hand.\n"
        f"# Environment: {environment}\n"
        f"# Domain: {domain}\n"
        f"# Target IP: {ip_address}\n\n"
        f"{domain} {{\n"
        "    hosts {\n"
        f"{host_lines}\n"
        "        ttl 60\n"
        "        fallthrough\n"
        "    }\n\n"
        f"    forward . {forwarder_list}\n"
        "    cache 30\n"
        "}\n\n"
        ". {\n"
        f"    forward . {forwarder_list}\n"
        "    cache 30\n"
        "}\n"
    )


def cmd_generate(args: argparse.Namespace) -> int:
    root_dir = resolve_root_dir(DEFAULT_ROOT, args.project_root)
    environment = resolve_prompted_environment(args.environment)
    domain = validate_domain(resolve_prompted_required(args.domain, "Enter domain (example.com): ", "domain"))
    ip_address = _validate_ip(resolve_prompted_required(args.ip_address, "Enter DNS target IP: ", "ip"))

    generated_dir = root_dir / "generated" / environment
    routes_file = generated_dir / "routes.env"
    corefile = generated_dir / "Corefile"

    log_info(f"Loading route hosts from: {routes_file}")
    hosts = _route_hosts(routes_file, domain)

    content = render_corefile(
        environment=environment,
        domain=domain,
        ip_address=ip_address,
        hosts=hosts,
    )

    corefile.parent.mkdir(parents=True, exist_ok=True)
    corefile.write_text(content, encoding="utf-8", newline="\n")

    log_ok(f"CoreDNS Corefile generated: {corefile}")
    log_info(f"Hosts: {', '.join(hosts)}")
    return 0


def register(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    dns_parser = subparsers.add_parser("dns", help="DNS/CoreDNS operations")
    dns_sub = dns_parser.add_subparsers(dest="dns_action", required=True)

    generate_parser = dns_sub.add_parser("generate", help="Generate CoreDNS Corefile")
    generate_parser.add_argument("--env", dest="environment")
    generate_parser.add_argument("--domain")
    generate_parser.add_argument("--ip", dest="ip_address")
    generate_parser.add_argument("--project-root", dest="project_root")
    generate_parser.set_defaults(handler=cmd_generate)
