#!/usr/bin/env python3
from __future__ import annotations

import argparse
import ipaddress
import subprocess
import sys
from pathlib import Path

if __package__ in {None, ""}:
    scripts_dir = Path(__file__).resolve().parents[1]
    cli_path = scripts_dir / "cli.py"
    raise SystemExit(subprocess.call([str(cli_path), "dns", *sys.argv[1:]]))

from core.env import parse_routes_file
from core.paths import resolve_root_dir
from core.ui import log_info, log_ok
from core.validators import fail, resolve_prompted_environment, resolve_prompted_required, validate_domain


DEFAULT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_ACL_NETS = ("100.64.0.0/10",)
DEFAULT_CACHE_TTL_SECONDS = 300
DEFAULT_FORWARDERS = ("1.1.1.1", "8.8.8.8")


def _validate_ip(raw_ip: str) -> str:
    value = raw_ip.strip()
    if not value:
        fail("IP address must not be empty")

    try:
        return str(ipaddress.ip_address(value))
    except ValueError:
        fail(f"Invalid IP address: {value}")
        raise AssertionError("unreachable")


def _validate_acl_nets(raw_acl_nets: list[str] | tuple[str, ...] | None) -> tuple[str, ...]:
    raw_values = raw_acl_nets if raw_acl_nets is not None else DEFAULT_ACL_NETS
    acl_nets: list[str] = []
    seen: set[str] = set()

    for raw_value in raw_values:
        for raw_item in raw_value.split(","):
            value = raw_item.strip()
            if not value:
                fail("ACL network must not be empty")

            try:
                network = str(ipaddress.ip_network(value, strict=False))
            except ValueError:
                fail(f"Invalid ACL network: {value}")
                raise AssertionError("unreachable")

            if network in seen:
                continue
            seen.add(network)
            acl_nets.append(network)

    if not acl_nets:
        fail("At least one ACL network is required")

    return tuple(acl_nets)


def _route_hosts(routes_file: Path, domain: str) -> list[str]:
    if not routes_file.is_file():
        fail(f"Routes file not found: {routes_file}. Run ./scripts/init.py --env <env> --domain {domain} --no-up first.")

    hosts: list[str] = []
    seen: set[str] = set()
    invalid_hosts: list[str] = []

    for _route_name, host, _upstream in parse_routes_file(routes_file):
        normalized = host.strip().rstrip(".").lower()
        if not normalized:
            continue
        if normalized != domain and not normalized.endswith(f".{domain}"):
            invalid_hosts.append(normalized)
            continue
        if normalized in seen:
            continue
        seen.add(normalized)
        hosts.append(normalized)

    if invalid_hosts:
        fail(f"Route hosts outside domain '{domain}': {', '.join(invalid_hosts)}")
    if not hosts:
        fail(f"No route hosts found in {routes_file}")

    return hosts


def _render_acl_block(acl_nets: tuple[str, ...]) -> str:
    allow_lines = "\n".join(f"        allow net {acl_net}" for acl_net in acl_nets)
    return (
        "    acl {\n"
        f"{allow_lines}\n"
        "        block\n"
        "    }\n"
    )


def render_corefile(
    *,
    environment: str,
    domain: str,
    ip_address: str,
    hosts: list[str],
    acl_nets: tuple[str, ...] = DEFAULT_ACL_NETS,
    cache_ttl_seconds: int = DEFAULT_CACHE_TTL_SECONDS,
    forwarders: tuple[str, ...] = DEFAULT_FORWARDERS,
) -> str:
    acl_block = _render_acl_block(acl_nets)
    forwarder_list = " ".join(forwarders)
    host_lines = "\n".join(f"        {ip_address} {host}" for host in hosts)

    return (
        "# Generated by Yuviron CLI. Do not edit by hand.\n"
        f"# Environment: {environment}\n"
        f"# Domain: {domain}\n"
        f"# Target IP: {ip_address}\n\n"
        f"{domain} {{\n"
        f"{acl_block}\n"
        "    hosts {\n"
        f"{host_lines}\n"
        "        ttl 60\n"
        "        fallthrough\n"
        "    }\n\n"
        f"    forward . {forwarder_list}\n"
        f"    cache {cache_ttl_seconds}\n"
        "}\n\n"
        ". {\n"
        f"{acl_block}\n"
        f"    forward . {forwarder_list}\n"
        f"    cache {cache_ttl_seconds}\n"
        "}\n"
    )


def cmd_generate(args: argparse.Namespace) -> int:
    root_dir = resolve_root_dir(DEFAULT_ROOT, args.project_root)
    environment = resolve_prompted_environment(args.environment)
    domain = validate_domain(resolve_prompted_required(args.domain, "Enter domain (example.com): ", "domain"))
    ip_address = _validate_ip(resolve_prompted_required(args.ip_address, "Enter DNS target IP: ", "ip"))
    acl_nets = _validate_acl_nets(getattr(args, "acl_nets", None))

    generated_dir = root_dir / "generated" / environment
    routes_file = generated_dir / "routes.env"
    corefile = generated_dir / "Corefile"

    log_info(f"Loading route hosts from: {routes_file}")
    hosts = _route_hosts(routes_file, domain)

    content = render_corefile(
        environment=environment,
        domain=domain,
        ip_address=ip_address,
        hosts=hosts,
        acl_nets=acl_nets,
    )

    corefile.parent.mkdir(parents=True, exist_ok=True)
    corefile.write_text(content, encoding="utf-8", newline="\n")

    log_ok(f"CoreDNS Corefile generated: {corefile}")
    log_info(f"Hosts: {', '.join(hosts)}")
    return 0


def register(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    dns_parser = subparsers.add_parser("dns", help="DNS/CoreDNS operations")
    dns_sub = dns_parser.add_subparsers(dest="dns_action", required=True)

    generate_parser = dns_sub.add_parser("generate", help="Generate CoreDNS Corefile")
    generate_parser.add_argument("--env", dest="environment")
    generate_parser.add_argument("--domain")
    generate_parser.add_argument("--ip", dest="ip_address")
    generate_parser.add_argument(
        "--acl-net",
        dest="acl_nets",
        action="append",
        help="CIDR or IP allowed to query generated CoreDNS config; repeat or comma-separate values",
    )
    generate_parser.add_argument("--project-root", dest="project_root")
    generate_parser.set_defaults(handler=cmd_generate)
